### PR TITLE
bring back the npm package-lock.json to fix the build issue

### PR DESCRIPTION
**Pull request by hualin-adsk**
#### Objective
In this PR I tried to fix the compiling issue in current CI. And for the Github CI it is hard to use yarn, so I also am trying to bring back the package-lock.json.

#### Abstract
It looks like because the yarn.lock doesn't take effect, so it gets a newer version for the following library:
```
vscode-languageserver-protocol
vscode-languageserver-types
```
So it complains the following building error:
```
node_modules/vscode-languageclient/lib/client.d.ts:2:19 - error TS2305: Module '"../../vscode-languageserver-protocol/lib/common/api"' has no exported member 'RPCMessageType'.

2 import { Message, RPCMessageType, ResponseError, RequestType, RequestType0, RequestHandler, RequestHandler0, GenericRequestHandler, NotificationType, NotificationType0, NotificationHandler, NotificationHandler0, GenericNotificationHandler, MessageReader, MessageWriter, Trace, Event, ClientCapabilities, TextDocumentRegistrationOptions, InitializeParams, InitializeResult, InitializeError, ServerCapabilities, DocumentSelector } from 'vscode-languageserver-protocol';
                    ~~~~~~~~~~~~~~

node_modules/vscode-languageclient/lib/client.d.ts:365:33 - error TS2314: Generic type 'RequestType0<R, E>' requires 2 type argument(s).

365     sendRequest<R, E, RO>(type: RequestType0<R, E, RO>, token?: CancellationToken): Thenable<R>;

extension/src/project/findReplace/searchTree.ts:218:34 - error TS2339: Property 'label' does not exist on type 'string | TreeItemLabel'.
  Property 'label' does not exist on type 'string'.

218                 return itemlebel.label;
                                     ~~~~~

extension/src/project/projectTree.ts:166:17 - error TS2322: Type 'string | TreeItemLabel' is not assignable to type 'string'.
  Type 'TreeItemLabel' is not assignable to type 'string'.

166                 title: treeNode.label,
                    ~~~~~

  node_modules/@types/vscode/index.d.ts:34:9
    34         title: string;
               ~~~~~
    The expected type comes from property 'title' which is declared here on type 'Command'
```

To fix the issue I adopt the following way:
1. bring back the package-lock.json and remove the yarn.lock file
2. change some codes for `TreeItemLabel`

#### Tests Performed
 - run npm run compile or gulp build to very the build
 
#### Screen Shot
Not applicable for this PR

### CODE REVIEW

**Review by Sen-real — APPROVED** [review]

**Review by JD-Howard — APPROVED** [review]
I cloned this repo, ran wincompile.bat and npm install. The first time I ran `npm install` it did produce a file access error, but the second time it worked just fine. I ran into a similar problem with another repo so I don't believe this is an issue, but we may want to add a note to the devREADME to try `npm install` again if it errors. Also, on that other repo I found restarting VSCode had some benefits for something in this lane.

**Comment by hualin-adsk** [comment]
Thanks! `produce a file access error`, could you paste the specific error message to me?

**Comment by JD-Howard** [comment]
this is from the log:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! code EPERM
npm ERR! syscall rename
npm ERR! path Z:\_OpenSource\AutoLispExt\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\package.json.3311039866
npm ERR! dest Z:\_OpenSource\AutoLispExt\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\package.json
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, rename 'Z:\_OpenSource\AutoLispExt\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\package.json.3311039866' -> 'Z:\_OpenSource\AutoLispExt\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\package.json'
npm ERR!  [OperationalError: EPERM: operation not permitted, rename 'Z:\_OpenSource\AutoLispExt\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\package.json.3311039866' -> 'Z:\_OpenSource\AutoLispExt\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\package.json'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, rename 'Z:\_OpenSource\AutoLispExt\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\package.json.3311039866' -> 'Z:\_OpenSource\AutoLispExt\node_modules\vscode-languageserver-protocol\node_modules\vscode-jsonrpc\package.json'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'rename',
npm ERR!     path: 'Z:\\_OpenSource\\AutoLispExt\\node_modules\\vscode-languageserver-protocol\\node_modules\\vscode-jsonrpc\\package.json.3311039866',
npm ERR!     dest: 'Z:\\_OpenSource\\AutoLispExt\\node_modules\\vscode-languageserver-protocol\\node_modules\\vscode-jsonrpc\\package.json'
npm ERR!   },
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'Z:\\_OpenSource\\AutoLispExt\\node_modules\\vscode-languageserver-protocol\\node_modules\\vscode-jsonrpc\\package.json.3311039866',
npm ERR!   dest: 'Z:\\_OpenSource\\AutoLispExt\\node_modules\\vscode-languageserver-protocol\\node_modules\\vscode-jsonrpc\\package.json',
npm ERR!   parent: 'vscode-languageserver-protocol'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\howar\AppData\Roaming\npm-cache\_logs\2021-01-12T04_44_21_026Z-debug.log
```

**Comment by hualin-adsk** [comment]
It looks like this is a real issue, because the packge-lock.json was created from MacOS instead of windows.

**Pull request merged**
