### PR TITLE
Update the change log for AutolispExt v1.5.0

### PR DESCRIPTION
**Pull request by Sen-real**
##### Objective
Update the change log for AutolispExt v1.5.0

##### Abstractions
The change log is updated to describe what's new since ver1.4.0.
Also updated i18n/enu/package.i18n.json with package.nls.json.

NOTE: extension version is not set to 1.5.0 yet.

### CODE REVIEW

**Comment by ambrosl-adsk** [comment]
The only comment I have is related to this text "Determines the targeted AutoCAD year version of the 'Open Online Help' command." in _package.i18n.json_.

I would change it to "Specifies the targeted AutoCAD release of the 'Open Online Help' command." if the user can change it.

**Comment by ambrosl-adsk** [comment]
Version in the package.json file reflects 1.4.2... should this be 1.5.0?  If not, there seems to be a discrepancy between the extension's version and change log.

**Comment by Sen-real** [comment]
> Version in the package.json file reflects 1.4.2... should this be 1.5.0? If not, there seems to be a discrepancy between the extension's version and change log.

Sure, it will be changed to 1.5.0 right before we make a package to publish.

**Comment by hualin-whl** [comment]
Happy to see we will release another new version!

**Pull request merged**
